#!/bin/bash

apt-get update
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password $USER'
sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password $PASS'
sudo apt-get -y install mysql-server




apt-get install -y python-pip
apt-get install -y python-software-properties #Necesario para que funciones add-adpt-repository
apt-get install build-essential
sudo apt-get install python-dev			#Necesario para la biblioteca de mysql
sudo apt-get install python-MySQLdb		#Necesario para la biblioteca de mysql
#make install
