#!/bin/bash
############################################################
#
# Plantilla para generación de Variables de Entorno
# Genera las variables de entorno mostradas abajo
#
# Para cambiar alguna, modificarla y volver a ejecutar
# el script
#
# Author: @neon520
#
############################################################


if [ "$1" == "" ]; then
	var=$USER
else
	var=$1
fi


head /home/$var/.bashrc > aux
cat aux > /home/$var/.bashrc     #con esto evitamos replicar variables de entorno
echo 'export USUARIO=""' >> /home/$var/.bashrc
echo 'export CONTRASENA=""' >> /home/$var/.bashrc
echo 'export VA_USUARIO_AZURE=""' >> /home/$var/.bashrc
echo 'export VA_PASS_AZURE=""' >> /home/$var/.bashrc
echo 'export VA_USUARIO_SSH=""' >> /home/$var/.bashrc
echo 'export VA_PASS_SSH=""' >> /home/$var/.bashrc
echo 'export VA_CER_PEM=""' >> /home/$var/.bashrc
echo 'export VA_VM_NAME=""' >> /home/$var/.bashrc
echo 'export VA_SUB_AZURE=""' >> /home/$var/.bashrc


bash
