#!/bin/bash
############################################################
#
# Plantilla para generación de Variables de Entorno
# Genera las variables de entorno mostradas abajo
#
# Para cambiar alguna, modificarla y volver a ejecutar
# el script
#
# Author: @neon520
#
############################################################

if [ "$1" == "" ]; then
	var=$USER
else
	var=$1
fi

if [ "$var" == "root" ]; then
	direccion=/root/.bashrc
else
	direccion=/home/$var/.bashrc
fi

head $direccion > aux
cat aux > $direccion     #con esto evitamos replicar variables de entorno
echo 'export USUARIO=""' >> $direccion
echo 'export CONTRASENA=""' >> $direccion
echo 'export VA_USUARIO_AZURE=""' >> $direccion
echo 'export VA_PASS_AZURE=""' >> $direccion
echo 'export VA_USUARIO_SSH=""' >> $direccion
echo 'export VA_PASS_SSH=""' >> $direccion
echo 'export VA_CER_PEM=""' >> $direccion
echo 'export VA_VM_NAME=""' >> $direccion
echo 'export VA_SUB_AZURE=""' >> $direccion


bash
